// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Outsider.CupomAPI.Model.Context;

#nullable disable

namespace Outsider.CupomAPI.Migrations
{
    [DbContext(typeof(OutsiderContext))]
    partial class OutsiderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Outsider.CupomAPI.Model.CupomModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("CodigoCupom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CodigoCupom");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataValidade");

                    b.Property<float>("PorcentagemDesconto")
                        .HasColumnType("real")
                        .HasColumnName("PorcentagemDesconto");

                    b.HasKey("Id");

                    b.ToTable("Cupom");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31c4f02a-db8a-4f28-ad70-70c6b0eb8388"),
                            CodigoCupom = "DN10",
                            DataInclusao = new DateTime(2025, 2, 13, 15, 54, 28, 505, DateTimeKind.Local).AddTicks(8186),
                            DataValidade = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PorcentagemDesconto = 10f
                        },
                        new
                        {
                            Id = new Guid("a77c16d5-49de-42ba-b762-e58e93ba454b"),
                            CodigoCupom = "DN20",
                            DataInclusao = new DateTime(2025, 2, 13, 15, 54, 28, 505, DateTimeKind.Local).AddTicks(8233),
                            DataValidade = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PorcentagemDesconto = 20f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
